"""
Personal AI Financial News Bot
Scrapes X (Twitter) → Groq LLaMA → Telegram/Discord alerts
Runs on GitHub Actions every 15 minutes, 100% free, zero infra.
"""

import asyncio
import json
import logging
import os
import re
import time
from collections import OrderedDict
from datetime import datetime, timezone, timedelta

import httpx
import yfinance as yf
from groq import Groq
from twscrape import API

# ─────────────────────────────────────────────────────────────────────────────
# XCLID PATCH — Fix twscrape's XClientTxId generation.
#
# X's API requires an "X-Client-Transaction-Id" header generated by parsing
# x.com's JavaScript chunk map and SVG animations. twscrape 0.17.0 uses
# json.loads() to parse the chunk map, but x.com changed to JavaScript object
# literal syntax (unquoted keys), which is valid JS but not valid JSON.
#
# This patch replaces the JSON parser with a regex extractor that handles
# both quoted and unquoted keys, fixing "Failed to parse scripts" everywhere.
# ─────────────────────────────────────────────────────────────────────────────

def _setup_xclid_patch() -> None:
    """
    Patch twscrape's get_scripts_list() to handle x.com's frequently-changing
    webpack bundle format.

    Tries three strategies in order:
      1. Original pattern (e=>e+"."+) — webpack 4 style
      2. Newer webpack 5 / x.com style: {map}[e]||e  variants
      3. Direct regex scan for ondemand.s.* URLs in the page text (no chunk map needed)
    """
    import twscrape.xclid as _xclid

    _HASH_PAT = re.compile(r'"?([^":\s{},\[\]]+)"?\s*:\s*"([a-f0-9]{5,10})"')

    def _extract_from_chunk(chunk_text: str):
        for key, val in _HASH_PAT.findall(chunk_text):
            yield _xclid.script_url(key, f"{val}a")

    def _patched_get_scripts_list(text: str):
        # Strategy 1: original webpack 4 pattern (e=>e+"."+{...}[e]+"a.js")
        if 'e=>e+"."+' in text and '[e]+"a.js"' in text:
            try:
                chunk = text.split('e=>e+"."+')[1].split('[e]+"a.js"')[0]
                results = list(_extract_from_chunk(chunk))
                if results:
                    log.info("[XClId] Strategy 1 (webpack4 chunk map) matched.")
                    yield from results
                    return
            except Exception:
                pass

        # Strategy 2: webpack 5 / newer x.com — {map}[e]||e or e=>({...}[e]||e)
        for marker_start, marker_end in [
            (r'\{[^{}]{40,}\}\[e\]\|\|e', None),
            (r'chunksById', None),
        ]:
            try:
                m = re.search(r'\{([^{}]{40,})\}\[e\]', text)
                if m:
                    results = list(_extract_from_chunk(m.group(1)))
                    if results:
                        log.info("[XClId] Strategy 2 (webpack5 chunk map) matched.")
                        yield from results
                        return
            except Exception:
                pass

        # Strategy 3: direct URL scan — find ondemand.s.* script URLs in the page
        direct = re.findall(
            r'https://abs\.twimg\.com/responsive-web/client-web/ondemand\.s\.[a-f0-9a-z]+\.js',
            text,
        )
        if direct:
            log.info(f"[XClId] Strategy 3 (direct URL scan) matched {len(direct)} URLs.")
            yield from dict.fromkeys(direct)  # deduplicate, preserve order
            return

        # Strategy 4: scan all abs.twimg.com client-web JS chunks
        all_chunks = re.findall(
            r'https://abs\.twimg\.com/responsive-web/client-web/[a-zA-Z0-9._/-]+\.js',
            text,
        )
        if all_chunks:
            log.warning(f"[XClId] Strategy 4 (all chunks fallback): yielding {len(all_chunks)} URLs.")
            yield from dict.fromkeys(all_chunks)
            return

        log.error("[XClId] All strategies failed — x.com page format unrecognised.")

    _xclid.get_scripts_list = _patched_get_scripts_list

    # Also patch parse_anim_idx — it filters scripts for "/ondemand.s." which may
    # not appear in the URLs returned by our fallback strategies. Instead, try ALL
    # scripts and return indices from the first one that contains them.
    async def _patched_parse_anim_idx(text: str) -> list[int]:
        scripts = list(_xclid.get_scripts_list(text))
        if not scripts:
            raise Exception("Couldn't get XClientTxId scripts")

        # Prefer ondemand.s. scripts (original behavior), then fall back to others
        ordered = (
            [s for s in scripts if "/ondemand.s." in s]
            + [s for s in scripts if "/ondemand.s." not in s]
        )

        for url in ordered[:10]:
            try:
                js_text = await _xclid.get_tw_page_text(url)
                items = [int(m.group(2)) for m in _xclid.INDICES_REGEX.finditer(js_text)]
                if items:
                    log.info(f"[XClId] Found animation indices in {url.split('/')[-1]}")
                    return items
            except Exception:
                continue

        raise Exception("Couldn't get XClientTxId indices from any available script")

    _xclid.parse_anim_idx = _patched_parse_anim_idx
    log.info("[XClId] Patched get_scripts_list() + parse_anim_idx() with fallback chain.")


# ─────────────────────────────────────────────────────────────────────────────
# CONFIG BLOCK — Edit these constants to customize the bot's behavior
# ─────────────────────────────────────────────────────────────────────────────

# Thematic search queries — split across multiple queries to bypass X's 512-char limit
SEARCH_QUERIES = [
    # Query 1: Macro & central banks
    '(Fed OR FOMC OR Powell OR "rate cut" OR "rate decision" OR CPI OR '
    '"jobs report" OR "interest rate" OR earnings OR NFP OR PPI OR GDP OR '
    'recession OR inflation OR disinflation OR stagflation OR "soft landing" OR '
    'tariff OR tariffs OR sanctions OR "trade war" OR default OR "credit risk") '
    'lang:en',

    # Query 2: Commodities, bonds, forex & geopolitics
    '(gold OR silver OR oil OR crude OR $GC OR $SI OR $CL OR $WTI OR '
    '$TLT OR "long bond" OR "30 year treasury" OR "long duration" OR '
    '$USDJPY OR "USD JPY" OR $DXY OR OPEC OR "oil supply" OR '
    'geopolitical OR "middle east" OR war OR "energy crisis" OR natgas) '
    'lang:en',

    # Query 3: Indices, tickers & sectors
    '($SPX OR "S&P 500" OR $DJI OR "Dow Jones" OR $RUT OR "Russell 2000" OR '
    '$NDX OR "Nasdaq 100" OR crash OR rally OR "bull run" OR '
    '$NVDA OR $TSLA OR $AAPL OR $AMZN OR $GOOGL OR $MSFT OR $AMD OR $SMCI OR '
    '$META OR $NFLX OR $COIN OR $PLTR OR $ARM OR '
    '$BTC OR $ETH OR $SOL OR crypto OR bitcoin) '
    'lang:en',

    # Query 4: Sectors & broad sentiment
    '(layoffs OR "job cuts" OR bankruptcy OR downgrade OR upgrade OR '
    '"sector rotation" OR financials OR "real estate" OR healthcare OR '
    'energy OR semiconductor OR "AI boom" OR buyback OR guidance OR '
    '"short squeeze" OR VIX OR volatility OR selloff OR capitulation) '
    'lang:en',
]

# Groq model to use for scoring and summarization
# Options: llama-3.3-70b-versatile, llama-3.1-8b-instant (faster/cheaper)
MODEL_ID = "llama-3.3-70b-versatile"

# === IMPACT THRESHOLD ===
# 5 = broad coverage (more alerts, some noise), 6 = balanced, 7 = strict, 8 = ultra-clean
MIN_IMPACT_SCORE = 8

# Maximum alerts to send per bot run (prevents Telegram spam on busy news days)
MAX_ALERTS = 3

# === QUALITY FILTERS ===
# Pre-LLM gate — only tweets with real reach go to Groq (saves API quota)
MIN_VIEWS = 1000
MIN_FOLLOWERS = 500

# How many minutes back to search for tweets (5-min buffer over 30-min cron)
# This small overlap ensures no tweets fall through the gap between runs
LOOKBACK_MINUTES = 20

# Seconds to pause between Groq API calls (free tier: 30 req/min = 2s min gap)
GROQ_RATE_LIMIT_SLEEP = 3

# Number of tweets to score in a single Groq batch call (reduces API usage ~10x)
BATCH_SIZE = 10

# Seconds to pause between Telegram sends (flood control: max 1 msg/sec)
TELEGRAM_RATE_LIMIT_SLEEP = 1

# === MARKET SNAPSHOT (live prices every run) ===
# Grouped by category for cleaner display
MARKET_TICKER_GROUPS = OrderedDict({
    "📈 Indices": {
        "SPY (S&P 500)": "SPY",
        "NDX (Nasdaq 100)": "^NDX",
        "IWM (Russell 2000)": "IWM",
        "DIA (DJ30)": "DIA",
    },
    "🪙 Commodities": {
        "🥇 Gold": "GC=F",
        "🥈 Silver": "SI=F",
        "🛢 WTI Crude": "CL=F",
    },
    "📊 Bonds & Forex": {
        "📈 TLT (Long Bonds)": "TLT",
        "💵 DXY": "DX-Y.NYB",
        "💱 USDJPY": "USDJPY=X",
    },
    "🌍 International": {
        "🇨🇳 China (CSI 300)": "000300.SS",
        "🇯🇵 Japan (Nikkei 225)": "^N225",
        "🇮🇳 India (Nifty 50)": "^NSEI",
    },
    "🪙 Crypto": {
        "₿ BTC": "BTC-USD",
        "⟠ ETH": "ETH-USD",
        "✕ XRP": "XRP-USD",
    },
    "😱 Volatility": {
        "😱 VIX": "^VIX",
    },
})

# Flat dict for backward compatibility (used by yfinance bulk fetch)
MARKET_TICKERS = {}
for _group_tickers in MARKET_TICKER_GROUPS.values():
    MARKET_TICKERS.update(_group_tickers)

# ─────────────────────────────────────────────────────────────────────────────
# LOGGING SETUP — structured output for readable GitHub Actions logs
# ─────────────────────────────────────────────────────────────────────────────

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s | %(levelname)s | %(message)s",
    datefmt="%Y-%m-%d %H:%M:%S",
)
log = logging.getLogger(__name__)


# ─────────────────────────────────────────────────────────────────────────────
# X ACCOUNT SETUP — re-login each run (GitHub Actions has no persistent fs)
# ─────────────────────────────────────────────────────────────────────────────

async def login_accounts(api: API) -> int:
    """
    Add up to 3 X accounts to the twscrape pool and log them in.

    Supports two auth modes per account (checked in order):
      1. Cookie auth  — set X_ACCOUNT_N_COOKIES="auth_token=xxx; ct0=yyy"
         Extracted from a browser session; bypasses the Cloudflare-protected
         login flow entirely.  Recommended for cloud/GitHub Actions environments.
      2. Password auth — set X_ACCOUNT_N_USER / PASS / EMAIL as before.

    Returns the number of accounts that are active after login, or 0 on failure.
    """
    accounts_added = 0

    for i in range(1, 4):
        username = os.getenv(f"X_ACCOUNT_{i}_USER", "").strip()
        password = os.getenv(f"X_ACCOUNT_{i}_PASS", "").strip()
        email = os.getenv(f"X_ACCOUNT_{i}_EMAIL", "").strip()
        cookies = os.getenv(f"X_ACCOUNT_{i}_COOKIES", "").strip()

        if not (username and password and email):
            continue  # Skip unconfigured slots

        try:
            await api.pool.add_account(
                username, password, email, email,
                cookies=cookies if cookies else None,
            )
            auth_mode = "cookie" if cookies else "password"
            log.info(f"[X Auth] Added account slot {i}: @{username} (mode={auth_mode})")
            accounts_added += 1
        except Exception as e:
            log.warning(f"[X Auth] Failed to add account {i} (@{username}): {e}")

    if accounts_added == 0:
        log.error("[X Auth] No valid X accounts configured. Set X_ACCOUNT_1_* secrets.")
        return 0

    try:
        await api.pool.login_all()
    except Exception as e:
        log.error(f"[X Auth] login_all() raised: {e}")
        return 0

    # Verify how many accounts are actually active — login_all() swallows
    # per-account failures (e.g. Cloudflare blocks) without raising.
    try:
        all_accts = await api.pool.get_all()
        active_count = sum(1 for a in all_accts if a.active)
    except Exception:
        # Older twscrape versions may not expose get_all(); fall back gracefully.
        log.warning("[X Auth] Could not verify active account count (twscrape version).")
        active_count = accounts_added

    if active_count == 0:
        log.error(
            "[X Auth] 0 accounts active after login — all logins failed.\n"
            "  Most likely cause: Cloudflare is blocking the password-based login\n"
            "  flow from this IP (common on GitHub Actions / cloud runners).\n"
            "  Fix: extract auth_token + ct0 cookies from a browser session and\n"
            "  set X_ACCOUNT_1_COOKIES='auth_token=<value>; ct0=<value>' in secrets."
        )
        return 0

    log.info(f"[X Auth] {active_count}/{accounts_added} account(s) active after login.")
    return active_count


# ─────────────────────────────────────────────────────────────────────────────
# TWEET SCRAPING — search X and filter to the lookback window
# ─────────────────────────────────────────────────────────────────────────────

async def scrape_tweets(api: API) -> list[dict]:
    """
    Search X using SEARCH_QUERIES and return tweets from the last LOOKBACK_MINUTES.
    Runs all thematic queries and deduplicates by tweet ID.
    Each returned dict has: id, text, url, created_at, author, likes.
    """
    cutoff = datetime.now(timezone.utc) - timedelta(minutes=LOOKBACK_MINUTES)
    log.info(f"[Scrape] Searching tweets since {cutoff.strftime('%H:%M:%S')} UTC")

    tweets = []
    seen_ids = set()

    for i, query in enumerate(SEARCH_QUERIES, 1):
        log.info(f"[Scrape] Running query {i}/{len(SEARCH_QUERIES)}")
        try:
            async for tweet in api.search(query, limit=200):
                if tweet.id in seen_ids:
                    continue

                # Filter to the lookback window
                tweet_time = tweet.date  # twscrape returns tz-aware datetime
                if tweet_time < cutoff:
                    continue

                views = tweet.viewCount or 0
                followers = tweet.user.followersCount or 0

                # Pre-LLM quality filter — skip low-quality tweets before Groq
                if views < MIN_VIEWS or followers < MIN_FOLLOWERS:
                    log.info(
                        f"[Scrape] Skipping @{tweet.user.username} | "
                        f"{views} views, {followers} followers (below threshold)"
                    )
                    continue

                tweet_data = {
                    "id": tweet.id,
                    "text": tweet.rawContent,
                    "url": f"https://x.com/{tweet.user.username}/status/{tweet.id}",
                    "created_at": tweet_time,
                    "author": tweet.user.username,
                    "likes": tweet.likeCount,
                    "views": views,
                    "followers": followers,
                }
                tweets.append(tweet_data)
                seen_ids.add(tweet.id)
                log.info(
                    f"[Scrape] Found: @{tweet.user.username} | "
                    f"{tweet.likeCount} likes | {views} views | "
                    f"{followers} followers | {tweet_time.strftime('%H:%M')} UTC"
                )
        except Exception as e:
            log.error(f"[Scrape] Search query {i} failed: {e}")

    log.info(f"[Scrape] {len(tweets)} tweet(s) total across {len(SEARCH_QUERIES)} queries.")
    return tweets


# ─────────────────────────────────────────────────────────────────────────────
# GROQ SCORING — ask LLaMA to score market impact and summarize
# ─────────────────────────────────────────────────────────────────────────────

def batch_score_tweets(tweets_batch: list[dict], groq_client: Groq, finviz_context: str | None = None) -> list[dict | None]:
    """
    Score multiple tweets in a single Groq API call to stay within free-tier limits.
    Returns a list of score dicts (or None for tweets that failed to parse),
    in the same order as the input batch.
    """
    # Build numbered tweet list for the prompt
    tweet_list = ""
    for i, t in enumerate(tweets_batch, 1):
        tweet_list += f"[{i}] @{t['author']}: {t['text'][:300]}\n"

    finviz_block = ""
    if finviz_context:
        finviz_block = f"""
Live Market Signals (from FinViz — use to cross-validate tweet claims):
{finviz_context}

"""

    prompt = f"""You are a veteran macro hedge-fund trader (10+ years). Rate each tweet for REAL market-moving impact (1-10).
{finviz_block}
{tweet_list}

Scoring rules — be ruthless:
- 8-10: ONLY verified breaking news with immediate, concrete price impact (Fed surprise, CPI miss/beat, war escalation, earnings shock, central bank pivot). Must be specific, sourced, and actionable RIGHT NOW.
- 6-7: Meaningful data or commentary with delayed impact. Notable but not urgent.
- 1-5: Opinion, speculation, hype, repeating known news, vague macro takes, excessive hashtags/cashtags.
- Default to 5 or below unless the tweet would cause a trader to act within the hour.
- Downgrade anything without a verifiable source, specific number, or named institution.
- Downgrade hype language ("trillions", "moon", "insane", "🚀🚀🚀").
- If a tweet mentions a ticker in FinViz unusual volume, +1. If it contradicts market data, -2.

Reply in EXACT JSON format with no extra text:
{{"results": [{{"id": 1, "score": <int 1-10>, "sentiment": "<Bullish OR Bearish OR Neutral>", "category": "<Commodities OR Macro OR Indices OR Bonds OR Forex OR Crypto OR Earnings>", "summary": "<one crisp actionable sentence, max 22 words>"}}, ...]}}"""

    try:
        response = groq_client.chat.completions.create(
            model=MODEL_ID,
            messages=[{"role": "user", "content": prompt}],
            response_format={"type": "json_object"},
            temperature=0.1,
            max_tokens=200 * len(tweets_batch),
        )
        raw = response.choices[0].message.content.strip()
        data = json.loads(raw)
        results_list = data.get("results", [])

        # Map results by their id (1-indexed) back to batch order
        results_by_id = {int(r.get("id", 0)): r for r in results_list}

        scores = []
        for i in range(1, len(tweets_batch) + 1):
            r = results_by_id.get(i)
            if r:
                score = {
                    "impact": int(r.get("score", 0)),
                    "sentiment": str(r.get("sentiment", "Neutral")).strip(),
                    "category": str(r.get("category", "Macro")).strip(),
                    "summary": str(r.get("summary", "")).strip(),
                }
                log.info(
                    f"[Groq] Tweet {i}: {score['impact']}/10 | "
                    f"{score['sentiment']} | {score['category']} | {score['summary'][:60]}..."
                )
                scores.append(score)
            else:
                log.warning(f"[Groq] Tweet {i}: missing from batch response.")
                scores.append(None)

        return scores

    except json.JSONDecodeError as e:
        log.warning(f"[Groq] Batch JSON parse error: {e}")
        return [None] * len(tweets_batch)
    except Exception as e:
        log.warning(f"[Groq] Batch API error: {e}")
        return [None] * len(tweets_batch)


# ─────────────────────────────────────────────────────────────────────────────
# ALERT FORMATTING — build the message sent to Telegram/Discord
# ─────────────────────────────────────────────────────────────────────────────

def build_alert_message(tweet: dict, score: dict) -> str:
    """
    Format a tweet + Groq score into a clean alert message.
    Includes sentiment, category, cashtags/hashtags.
    """
    impact = score["impact"]
    sentiment = score.get("sentiment", "Neutral")
    category = score.get("category", "Macro")
    summary = score["summary"]
    url = tweet["url"]
    ts = tweet["created_at"].strftime("%Y-%m-%d %H:%M UTC")

    # Sentiment emoji
    sent_emoji = {"Bullish": "🟢", "Bearish": "🔴"}.get(sentiment, "⚪")

    # Extract cashtags ($NVDA) and hashtags (#CPI) from tweet text
    cashtags = re.findall(r"\$[A-Z]{1,5}", tweet["text"])
    hashtags = re.findall(r"#\w+", tweet["text"])
    tags = " ".join(dict.fromkeys(cashtags + hashtags))[:100]  # dedupe, limit length
    tags_line = f"📊 {tags}" if tags else ""

    sep = "━━━━━━━━━━━━━━━━━━━━"

    lines = [
        sep,
        f"🚨 [IMPACT {impact}/10] {sent_emoji} {sentiment} | {category}",
        "",
        f"{summary}",
        "",
        f"🔗 {url}",
        f"🕒 {ts}",
    ]
    if tags_line:
        lines.append(tags_line)
    lines.append(sep)

    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# NARRATIVE DETECTION — cross-tweet theme analysis via Groq
# ─────────────────────────────────────────────────────────────────────────────

def detect_narratives(tweets: list[dict], groq_client: Groq, market_snapshot: str | None = None, finviz_context: str | None = None) -> str | None:
    """
    Analyze all scraped tweets as a batch to identify dominant market-moving
    narratives/themes. Returns a formatted narrative summary, or None on error.
    """
    if not tweets:
        return None

    # Concatenate all tweet texts with URLs and engagement metrics, truncated to ~8000 chars
    combined = ""
    for t in tweets:
        url = t.get("url", f"https://x.com/{t['author']}/status/{t.get('id', '')}")
        likes = t.get("likes", 0)
        views = t.get("views", 0)
        followers = t.get("followers", 0)
        entry = f"@{t['author']} ({url}) [likes:{likes} views:{views} followers:{followers}]: {t['text']}\n---\n"
        if len(combined) + len(entry) > 8000:
            break
        combined += entry

    market_context = ""
    if market_snapshot:
        market_context = f"""
Current Market Data (for reference — correlate with tweet narratives):
{market_snapshot}
"""

    finviz_block = ""
    if finviz_context:
        finviz_block = f"""
Live FinViz Signals (use real sector data below instead of guessing sector performance):
{finviz_context}
"""

    prompt = f"""You are a veteran macro hedge-fund strategist. Analyze the following batch of financial tweets and identify the dominant market-moving narratives/themes.
{market_context}{finviz_block}
Tweets:
{combined}

Instructions:
- Identify 2-3 dominant narratives emerging across these tweets (e.g., AI boom, yen carry unwind, disinflation, geopolitical oil risks, rate cut expectations)
- For each narrative, state the conviction level (High/Medium/Low) and direction (Bullish/Bearish/Mixed)
- Weight tweets by engagement (likes, views) and author influence (followers) when assessing conviction
- Quote a short phrase from one tweet as evidence for each narrative
- Cite the source tweet author and URL for each piece of evidence
- If market data is provided, reference actual price moves that confirm or contradict the narrative
- Identify the single overall dominant theme
- Provide a sector heatmap (use real FinViz sector % data if available, otherwise estimate from tweets) and an overall sentiment score

Reply in this EXACT plain-text format (no markdown, no JSON):

🔍 Market Narratives

1. [Narrative Name] – Bullish/Bearish/Mixed – High/Medium/Low conviction
   Evidence: "short quote from a tweet"
   Source: @author — <tweet URL>

2. [Narrative Name] – Bullish/Bearish/Mixed – High/Medium/Low conviction
   Evidence: "short quote from a tweet"
   Source: @author — <tweet URL>

📊 Sector Heatmap
🟢 Bullish: sector1, sector2
🔴 Bearish: sector3
⚪ Neutral: sector4

🎯 Overall dominant theme: one-sentence summary of the strongest narrative
📈 Tweet Sentiment Score: X/10 (1=extreme fear, 10=extreme greed)"""

    try:
        response = groq_client.chat.completions.create(
            model=MODEL_ID,
            messages=[{"role": "user", "content": prompt}],
            temperature=0.2,
            max_tokens=800,
        )
        result = response.choices[0].message.content.strip()
        log.info(f"[Narratives] Detected narratives ({len(result)} chars)")
        return result
    except Exception as e:
        log.warning(f"[Narratives] Groq API error: {e}")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# TELEGRAM — send alert via Bot API
# ─────────────────────────────────────────────────────────────────────────────

def send_telegram(message: str) -> bool:
    """
    Send a message to the configured Telegram chat/channel.
    Returns True on success, False on failure.
    """
    token = os.getenv("TELEGRAM_BOT_TOKEN", "").strip()
    chat_id = os.getenv("TELEGRAM_CHAT_ID", "").strip()

    if not (token and chat_id):
        log.warning("[Telegram] Skipping — TELEGRAM_BOT_TOKEN or TELEGRAM_CHAT_ID not set.")
        return False

    url = f"https://api.telegram.org/bot{token}/sendMessage"
    payload = {
        "chat_id": chat_id,
        "text": message,
        "parse_mode": "HTML",
        "disable_web_page_preview": False,
    }

    try:
        response = httpx.post(url, json=payload, timeout=10)
        if response.status_code == 200:
            log.info("[Telegram] Alert sent successfully.")
            return True
        else:
            log.error(f"[Telegram] Failed ({response.status_code}): {response.text[:200]}")
            return False
    except Exception as e:
        log.error(f"[Telegram] Request error: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# DISCORD — send alert via webhook (optional fallback)
# ─────────────────────────────────────────────────────────────────────────────

def send_discord(message: str) -> bool:
    """
    Send a message to the configured Discord webhook.
    Returns True on success, False on failure.
    """
    webhook_url = os.getenv("DISCORD_WEBHOOK_URL", "").strip()

    if not webhook_url:
        return False  # Silently skip — Discord is optional

    payload = {"content": message, "username": "Financial News Bot"}

    try:
        response = httpx.post(webhook_url, json=payload, timeout=10)
        if response.status_code in (200, 204):
            log.info("[Discord] Alert sent successfully.")
            return True
        else:
            log.error(f"[Discord] Failed ({response.status_code}): {response.text[:200]}")
            return False
    except Exception as e:
        log.error(f"[Discord] Request error: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# MARKET SNAPSHOT — live prices via yfinance
# ─────────────────────────────────────────────────────────────────────────────

def get_fear_greed() -> str | None:
    """
    Fetch the CNN Fear & Greed Index score and label.
    Returns a formatted string like '😱 Fear & Greed: 32 (Fear)', or None on failure.
    """
    url = "https://production.dataviz.cnn.io/index/fearandgreed/graphdata"
    # CNN's API returns 418 with a bare User-Agent — use a realistic browser string
    headers = {
        "User-Agent": (
            "Mozilla/5.0 (Windows NT 10.0; Win64; x64) "
            "AppleWebKit/537.36 (KHTML, like Gecko) "
            "Chrome/131.0.0.0 Safari/537.36"
        ),
        "Accept": "application/json, text/plain, */*",
        "Referer": "https://www.cnn.com/markets/fear-and-greed",
    }
    try:
        resp = httpx.get(url, timeout=10, headers=headers)
        resp.raise_for_status()
        data = resp.json()
        score = round(data["fear_and_greed"]["score"])
        label = data["fear_and_greed"]["rating"]
        # Clean up label: "Extreme Fear" → "Extreme Fear"
        label = label.replace("_", " ").title()
        return f"😱 Fear & Greed: {score} ({label})"
    except Exception as e:
        log.warning(f"[Snapshot] Failed to fetch Fear & Greed Index: {e}")
        return None


def get_market_snapshot() -> str | None:
    """
    Fetch current prices + daily % change for MARKET_TICKERS, grouped by category.
    Returns a formatted string ready to send, or None on failure.
    """
    lines = ["📊 *Market Snapshot*"]
    sep = "───────────────────"

    try:
        tickers = yf.Tickers(" ".join(MARKET_TICKERS.values()))

        for group_name, group_tickers in MARKET_TICKER_GROUPS.items():
            lines.append("")
            lines.append(f"*{group_name}*")
            lines.append(sep)
            for label, symbol in group_tickers.items():
                try:
                    ticker = tickers.tickers[symbol]
                    info = ticker.fast_info
                    price = info.last_price

                    # Get today's open price for open-to-current % change
                    hist = ticker.history(period="1d")
                    open_price = hist["Open"].iloc[-1] if not hist.empty else None

                    if price and open_price and open_price > 0:
                        pct = ((price - open_price) / open_price) * 100
                        arrow = "🟢" if pct >= 0 else "🔴"
                        lines.append(f"{arrow} {label}: ${price:,.2f} ({pct:+.2f}%)")
                    else:
                        lines.append(f"⚪ {label}: ${price:,.2f}" if price else f"⚪ {label}: N/A")
                except Exception:
                    lines.append(f"⚪ {label}: N/A")

        # Append Fear & Greed Index
        fg_line = get_fear_greed()
        if fg_line:
            lines.append("")
            lines.append(fg_line)

        lines.append(f"\n🕒 {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M UTC')}")
        return "\n".join(lines)

    except Exception as e:
        log.warning(f"[Snapshot] Failed to fetch market data: {e}")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# FINVIZ SIGNALS — cross-validate tweet claims against real market activity
# ─────────────────────────────────────────────────────────────────────────────

def scrape_finviz_signals() -> dict | None:
    """
    Scrape FinViz for sector performance, top gainers, and unusual volume.
    Returns a dict with formatted strings for prompt injection, or None on failure.
    """
    try:
        from finvizfinance.group.performance import Performance
        from finvizfinance.screener.overview import Overview

        # 1. Sector performance
        perf = Performance()
        perf_df = perf.screener_view()
        sectors_str = ""
        if perf_df is not None and not perf_df.empty:
            parts = []
            for _, row in perf_df.iterrows():
                name = row.get("Name", "")
                pct = row.get("Perf Day", row.get("Change", ""))
                if name and pct:
                    # Format percentage — may already be a string like "1.23%"
                    if isinstance(pct, (int, float)):
                        pct = f"{pct:+.2f}%"
                    parts.append(f"{name} {pct}")
            sectors_str = ", ".join(parts)
            log.info(f"[FinViz] Sector performance: {sectors_str[:120]}...")

        time.sleep(1)

        # 2. Top gainers
        gainers_screener = Overview()
        gainers_screener.set_filter(signal="Top Gainers")
        gainers_df = gainers_screener.screener_view(limit=10)
        gainers_str = ""
        if gainers_df is not None and not gainers_df.empty:
            parts = []
            for _, row in gainers_df.iterrows():
                ticker = row.get("Ticker", "")
                change = row.get("Change", "")
                if ticker:
                    if isinstance(change, (int, float)):
                        change = f"{change:+.2f}%"
                    parts.append(f"${ticker} {change}")
            gainers_str = ", ".join(parts)
            log.info(f"[FinViz] Top gainers: {gainers_str[:120]}...")

        time.sleep(1)

        # 3. Unusual volume
        vol_screener = Overview()
        vol_screener.set_filter(signal="Unusual Volume")
        vol_df = vol_screener.screener_view(limit=10)
        vol_str = ""
        if vol_df is not None and not vol_df.empty:
            parts = []
            for _, row in vol_df.iterrows():
                ticker = row.get("Ticker", "")
                volume = row.get("Volume", "")
                change = row.get("Change", "")
                if ticker:
                    vol_info = f"${ticker}"
                    if change:
                        if isinstance(change, (int, float)):
                            change = f"{change:+.2f}%"
                        vol_info += f" {change}"
                    if volume:
                        vol_info += f" (vol: {volume})"
                    parts.append(vol_info)
            vol_str = ", ".join(parts)
            log.info(f"[FinViz] Unusual volume: {vol_str[:120]}...")

        # Build the context block for Groq prompt injection
        context_parts = []
        if sectors_str:
            context_parts.append(f"Sector Performance (today): {sectors_str}")
        if gainers_str:
            context_parts.append(f"Top Gainers: {gainers_str}")
        if vol_str:
            context_parts.append(f"Unusual Volume: {vol_str}")

        if not context_parts:
            log.warning("[FinViz] All FinViz queries returned empty data.")
            return None

        context_block = "\n".join(context_parts)

        return {
            "sectors": sectors_str,
            "gainers": gainers_str,
            "unusual_volume": vol_str,
            "context_block": context_block,
        }

    except Exception as e:
        log.warning(f"[FinViz] Failed to scrape FinViz signals (non-fatal): {e}")
        return None


# ─────────────────────────────────────────────────────────────────────────────
# POLYMARKET — fetch macro prediction market probabilities
# ─────────────────────────────────────────────────────────────────────────────

# Slugs for macro-relevant Polymarket markets (free public API, no auth)
# Sources: Macro Indicators (tag 102000), Khamenei/Iran (tag 102304), Beirut (tag 104291)
_POLYMARKET_SLUGS = [
    # ── Macro / Fed / Inflation ──────────────────────────────────────────────
    "will-the-feds-lower-bound-reach-0-or-lower-before-2027-196-363-557-457-329-251-881",
    "will-inflation-reach-more-than-5-in-2026-282",
    "will-annual-inflation-increase-by-2pt7-in-march-955",
    "will-monthly-inflation-increase-by-0pt4-in-march-426",
    "will-chinas-2026-annual-gdp-growth-yy-be-between-4pt0-and-5pt0",
    "will-china-gdp-growth-in-q1-2026-be-at-least-6pt0",
    "tech-layoffs-up-or-down-in-february-2026",
    # ── Iran / Hormuz / Geopolitical ────────────────────────────────────────
    "will-the-kharg-island-oil-terminal-be-hit-by-april-30-484",
    "iran-leadership-change-by-may-31-593-194-829",
    "us-x-iran-meeting-by-april-30-2026",
    "iran-leadership-change-by-december-31-974-976-658-482-568",
    # ── Geopolitical misc ───────────────────────────────────────────────────
    "will-russia-capture-pokrovka-by-march-31",
    "will-venezuela-become-51st-state",
]

# Tag IDs for rotating/daily markets — fetches top 1 by volume per tag
# Beirut (104291), Black Sea (101958)
_POLYMARKET_TAG_IDS = [104291, 101958]


def _polymarket_url(m: dict, fallback_slug: str = "") -> str:
    """Extract the correct Polymarket event URL from a market object.
    Market slugs have numeric suffixes (-484 etc) that 404 on polymarket.com/event/.
    The events[0].slug is the canonical event URL slug."""
    events = m.get("events") or []
    if events and isinstance(events[0], dict):
        event_slug = events[0].get("slug", "")
        if event_slug:
            return f"https://polymarket.com/event/{event_slug}"
    # Fallback: strip trailing -NNN suffix from market slug
    slug = m.get("slug") or fallback_slug
    import re
    clean = re.sub(r"-\d+$", "", slug)
    return f"https://polymarket.com/event/{clean}"


def _polymarket_prob(m: dict) -> float | None:
    try:
        prices = json.loads(m.get("outcomePrices", "[]"))
        return float(prices[0]) if prices else None
    except Exception:
        return None


def fetch_polymarket_markets() -> list[dict]:
    """
    Fetch macro prediction market probabilities from Polymarket's public gamma API.
    Returns list of {question, probability, volume, url} dicts, or [] on failure.
    """
    results = []
    base = "https://gamma-api.polymarket.com/markets"

    for slug in _POLYMARKET_SLUGS:
        try:
            resp = httpx.get(
                base,
                params={"slug": slug},
                timeout=8,
                headers={"User-Agent": "FinancialNewsBot/1.0"},
            )
            if not resp.is_success:
                continue
            data = resp.json()
            markets = data if isinstance(data, list) else data.get("markets", [])
            if not markets:
                continue
            m = markets[0]
            prob = _polymarket_prob(m)
            results.append({
                "question": m.get("question", slug),
                "probability": prob,
                "volume": m.get("volume", 0),
                "url": _polymarket_url(m, slug),
            })
            log.info(f"[Polymarket] {m.get('question', slug)[:60]} → {prob:.0%}" if prob else f"[Polymarket] {slug} → no prob")
        except Exception as e:
            log.warning(f"[Polymarket] Failed to fetch {slug}: {e}")

    # ── Tag-based fetch for rotating daily markets ───────────────────────────
    for tag_id in _POLYMARKET_TAG_IDS:
        try:
            resp = httpx.get(
                base,
                params={"active": "true", "closed": "false", "tag_id": tag_id, "limit": 1, "order": "volume", "ascending": "false"},
                timeout=8,
                headers={"User-Agent": "FinancialNewsBot/1.0"},
            )
            if not resp.is_success:
                continue
            markets = resp.json()
            if not markets:
                continue
            m = markets[0]
            prob = _polymarket_prob(m)
            results.append({
                "question": m.get("question", ""),
                "probability": prob,
                "volume": m.get("volume", 0),
                "url": _polymarket_url(m),
            })
            log.info(f"[Polymarket/tag={tag_id}] {m.get('question', '')[:60]} → {prob:.0%}" if prob else f"[Polymarket/tag={tag_id}] no prob")
        except Exception as e:
            log.warning(f"[Polymarket] Failed to fetch tag {tag_id}: {e}")

    log.info(f"[Polymarket] Fetched {len(results)} markets.")
    return results


def polymarket_to_text(markets: list[dict]) -> str:
    """Format Polymarket markets as plain text for AI prompt injection."""
    if not markets:
        return ""
    lines = ["Polymarket Prediction Markets:"]
    for m in markets:
        prob_str = f"{m['probability']:.0%}" if m.get("probability") is not None else "N/A"
        lines.append(f"  • {m['question']} → {prob_str}")
    return "\n".join(lines)


# ─────────────────────────────────────────────────────────────────────────────
# GITHUB GIST — write structured intel snapshot for the investing tool
# ─────────────────────────────────────────────────────────────────────────────

def write_to_gist(
    narrative: str | None,
    top_alerts: list[dict],
    polymarket: list[dict],
) -> bool:
    """
    Write a structured JSON snapshot to a GitHub Gist.
    The investing tool reads this Gist URL on load to get fresh intel from the bot.

    Requires env vars:
      GITHUB_GIST_TOKEN — GitHub personal access token with gist scope
      GITHUB_GIST_ID    — ID of the Gist to update (create manually first)

    Returns True on success.
    """
    token = (os.getenv("GIST_TOKEN") or os.getenv("GITHUB_GIST_TOKEN") or "").strip()
    gist_id = (os.getenv("GIST_ID") or os.getenv("GITHUB_GIST_ID") or "").strip()

    if not token or not gist_id:
        log.warning("[Gist] Skipping — GIST_TOKEN or GIST_ID not set.")
        return False

    payload = {
        "updated_at": datetime.now(timezone.utc).isoformat(),
        "narrative": narrative or "",
        "top_alerts": [
            {
                "summary": a["score"]["summary"],
                "sentiment": a["score"]["sentiment"],
                "category": a["score"]["category"],
                "impact": a["score"]["impact"],
                "url": a["tweet"]["url"],
                "author": a["tweet"]["author"],
                "text": a["tweet"]["text"][:280],
                "ts": a["tweet"]["created_at"].isoformat(),
            }
            for a in top_alerts
        ],
        "polymarket": polymarket,
    }

    try:
        resp = httpx.patch(
            f"https://api.github.com/gists/{gist_id}",
            json={
                "files": {
                    "financial_intel.json": {
                        "content": json.dumps(payload, indent=2),
                    }
                }
            },
            headers={
                "Authorization": f"Bearer {token}",
                "Accept": "application/vnd.github+json",
                "X-GitHub-Api-Version": "2022-11-28",
            },
            timeout=15,
        )
        if resp.is_success:
            log.info(f"[Gist] Snapshot written — {len(top_alerts)} alerts, {len(polymarket)} PM markets.")
            return True
        else:
            log.error(f"[Gist] Failed ({resp.status_code}): {resp.text[:200]}")
            return False
    except Exception as e:
        log.error(f"[Gist] Request error: {e}")
        return False


# ─────────────────────────────────────────────────────────────────────────────
# MAIN ORCHESTRATION
# ─────────────────────────────────────────────────────────────────────────────

async def main():
    log.info("=" * 60)
    log.info("Financial News Bot starting up")
    log.info(f"Config: MIN_IMPACT={MIN_IMPACT_SCORE} | MAX_ALERTS={MAX_ALERTS} | LOOKBACK={LOOKBACK_MINUTES}min")
    log.info("=" * 60)

    # ── Step 0: Market Snapshot (every 4 hours only) ────────────────────────
    snapshot = None
    current_hour = datetime.now(timezone.utc).hour
    if current_hour % 4 == 0:
        snapshot = get_market_snapshot()
        if snapshot:
            log.info("[Snapshot] Market data fetched successfully.")
            send_telegram(snapshot)
            send_discord(snapshot)
        else:
            log.info("[Snapshot] Skipped (no data available).")
    else:
        log.info(f"[Snapshot] Skipped (next snapshot at hour {((current_hour // 4) + 1) * 4 % 24}:00 UTC).")

    # ── Step 0b: FinViz Signals (hourly only to avoid rate limiting) ────────
    finviz_data = None
    current_minute = datetime.now(timezone.utc).minute
    if current_minute < 15:  # Only on the first run of each hour
        finviz_data = scrape_finviz_signals()
    finviz_context = finviz_data["context_block"] if finviz_data else None
    if finviz_context:
        log.info(f"[FinViz] Context block ready ({len(finviz_context)} chars).")
    else:
        log.info("[FinViz] No FinViz data available — scoring will proceed without cross-validation.")

    # ── Step 1: Validate required secrets ─────────────────────────────────────
    groq_api_key = os.getenv("GROQ_API_KEY", "").strip()
    if not groq_api_key:
        log.error("GROQ_API_KEY not set. Aborting.")
        return
    groq_client = Groq(api_key=groq_api_key)

    # ── Step 2: Patch XClIdGen + Login to X accounts ──────────────────────────
    _setup_xclid_patch()
    api = API()
    accounts = await login_accounts(api)
    if accounts == 0:
        log.error("No X accounts available. Aborting.")
        return

    # ── Step 3: Scrape tweets ──────────────────────────────────────────────────
    tweets = await scrape_tweets(api)
    if not tweets:
        log.info("[Main] No tweets found in lookback window — skipping scoring/alerts.")
        # Still fetch Polymarket and write Gist snapshot even with no tweets
        polymarket_data = fetch_polymarket_markets()
        write_to_gist(narrative=None, top_alerts=[], polymarket=polymarket_data)
        log.info("=" * 60)
        return

    # ── Step 4: Batch-score with Groq, send qualifying alerts ──────────────
    alerts_sent = 0
    gist_alerts: list[dict] = []  # Collect for Gist snapshot
    total_batches = (len(tweets) + BATCH_SIZE - 1) // BATCH_SIZE
    log.info(f"[Main] Scoring {len(tweets)} tweets in {total_batches} batches of {BATCH_SIZE}.")

    for batch_idx in range(0, len(tweets), BATCH_SIZE):
        if alerts_sent >= MAX_ALERTS:
            log.info(f"[Main] Reached MAX_ALERTS ({MAX_ALERTS}). Stopping.")
            break

        batch = tweets[batch_idx : batch_idx + BATCH_SIZE]
        batch_num = batch_idx // BATCH_SIZE + 1
        log.info(f"[Main] Scoring batch {batch_num}/{total_batches} ({len(batch)} tweets)...")

        # Rate-limit pause before Groq call
        await asyncio.sleep(GROQ_RATE_LIMIT_SLEEP)

        scores = batch_score_tweets(batch, groq_client, finviz_context=finviz_context)

        for tweet, score in zip(batch, scores):
            if alerts_sent >= MAX_ALERTS:
                break

            if score is None:
                log.info(f"[Main] Skipping tweet {tweet['id']} — Groq returned no result.")
                continue

            if score["impact"] < MIN_IMPACT_SCORE:
                log.info(
                    f"[Main] Skipping tweet {tweet['id']} — "
                    f"impact {score['impact']}/10 < threshold {MIN_IMPACT_SCORE}."
                )
                continue

            # Build and send alert
            message = build_alert_message(tweet, score)
            log.info(f"[Main] Sending alert for tweet {tweet['id']} (impact {score['impact']}/10)...")

            tg_ok = send_telegram(message)
            dc_ok = send_discord(message)

            if tg_ok or dc_ok:
                alerts_sent += 1
                gist_alerts.append({"tweet": tweet, "score": score})
                log.info(f"[Main] Alert #{alerts_sent} sent (Telegram={tg_ok}, Discord={dc_ok}).")

            # Telegram flood control
            await asyncio.sleep(TELEGRAM_RATE_LIMIT_SLEEP)

    # ── Step 4b: Narrative Detection ──────────────────────────────────────────
    narrative_msg = None
    if tweets:
        await asyncio.sleep(GROQ_RATE_LIMIT_SLEEP)
        narrative_msg = detect_narratives(tweets, groq_client, market_snapshot=snapshot, finviz_context=finviz_context)
        if narrative_msg:
            send_telegram(narrative_msg)
            send_discord(narrative_msg)

    # ── Step 4c: Polymarket Macro Markets ─────────────────────────────────────
    polymarket_data = fetch_polymarket_markets()

    # ── Step 4d: Write Gist Snapshot ──────────────────────────────────────────
    write_to_gist(
        narrative=narrative_msg,
        top_alerts=gist_alerts,
        polymarket=polymarket_data,
    )

    # ── Step 5: Summary ────────────────────────────────────────────────────────
    log.info("=" * 60)
    if alerts_sent == 0:
        log.info("[Main] No qualifying alerts this run. Markets are quiet (or threshold is high).")
    else:
        log.info(f"[Main] Done. {alerts_sent} alert(s) sent this run.")
    log.info("=" * 60)


if __name__ == "__main__":
    asyncio.run(main())
